import os
import smtplib
from email.message import EmailMessage


def create_email(sender, recipient, subject, message):
    email = EmailMessage()
    email["From"] = sender
    email["To"] = recipient
    email["Subject"] = subject
    email.set_content(message)
    return email


def send_email(sender, password, recipient, subject, message):
    email = create_email(sender, recipient, subject, message)

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender, password)
        smtp.send_message(email)


def main():
    sender = os.getenv("SMTP_EMAIL")
    password = os.getenv("SMTP_APP_PASSWORD")
    recipient = os.getenv("TEST_RECIPIENT")

    if not all([sender, password, recipient]):
        print("Set SMTP_EMAIL, SMTP_APP_PASSWORD and TEST_RECIPIENT")
        print("as environment variables before sending.")
        return

    subject = "Skill Nexis Python Internship - Email Automation Test"
    message = (
        "Hello,\n\n"
        "This is a personalized test email generated by a Python "
        "automation script.\n\n"
        "Regards,\n"
        "Python Internship Project"
    )

    # Uncomment only after configuring and testing your SMTP account.
    # send_email(sender, password, recipient, subject, message)

    print("Email object prepared successfully.")
    print("Sending is disabled by default for safety.")


if __name__ == "__main__":
    main()
